USE SANKHYA_TESTE;

CREATE TABLE TGFPAR (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CODPARC INT NOT NULL,
    NOMEPARC VARCHAR(255) NOT NULL,
    RAZAOSOCIAL VARCHAR(255),
    CGC_CPF VARCHAR(18),
    TELEFONE VARCHAR(15),
    ALTERADOR VARCHAR(25)
);
