version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: sankhya_user
      POSTGRES_PASSWORD: sankhya_pass
      POSTGRES_DB: sankhya_db
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sankhya_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - internal_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
    driver: local
  pgadmin_data:
    driver: local

networks:
  internal_network:
    driver: bridge